name = "av5ja-api"
main = "src/index.ts"
account_id = "2488ea57494b2dacae95a6e363e7dcb2"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-02"
send_metrics = true

[observability]
enabled = true
head_sampling_rate = 1

[env.staging]
name = "av5ja-api-staging"
workers_dev = true

[env.staging.observability]
enabled = true
head_sampling_rate = 1

[[env.staging.d1_databases]]
binding = "SCHEDULES"
database_name = "av5ja-schedules-staging"
database_id = "211b7eca-6312-42aa-911c-0b942ab73b7d"
migrations_dir = "migrations"

[env.production]
name = "av5ja-api"
routes = [
  { pattern = "api.splatnet3.com", custom_domain = true }
]

[env.production.observability]
enabled = true
head_sampling_rate = 1

[env.production.triggers]
crons = ["*/30 * * * *"]

[[env.production.d1_databases]]
binding = "SCHEDULES"
database_name = "av5ja-schedules"
database_id = "865f2a3c-09b2-49f9-a328-bf20070e9456"
migrations_dir = "migrations"

[dev]
ip = "0.0.0.0"
port = 18787
